# build.spec — PyInstaller configuration for TKDN Finder Windows .exe
# Usage: pyinstaller build.spec
# Output: dist/tkdn-finder.exe

block_cipher = None

a = Analysis(
    ['src/tkdn_finder/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('src/tkdn_finder/templates', 'tkdn_finder/templates'),
        ('src/tkdn_finder/static', 'tkdn_finder/static'),
        ('migrations', 'migrations'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.main',
        'starlette.datastructures',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.templating',
        'fastapi',
        'fastapi.responses',
        'fastapi.staticfiles',
        'fastapi.templating',
        'apscheduler',
        'apscheduler.schedulers.asyncio',
        'apscheduler.triggers.cron',
        'apscheduler.executors.asyncio',
        'rapidfuzz',
        'rapidfuzz.fuzz',
        'bs4',
        'lxml',
        'lxml.etree',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'aiosqlite',
        'pydantic_settings',
        'httpx',
        'jinja2',
        'jinja2.ext',
        'tkdn_finder',
        'tkdn_finder.constants',
        'tkdn_finder.config',
        'tkdn_finder.db',
        'tkdn_finder.models',
        'tkdn_finder.scraper',
        'tkdn_finder.downloader',
        'tkdn_finder.parser',
        'tkdn_finder.merger',
        'tkdn_finder.search',
        'tkdn_finder.synonyms',
        'tkdn_finder.scheduler',
        'tkdn_finder.routes.search',
        'tkdn_finder.routes.detail',
        'tkdn_finder.routes.admin',
        'tkdn_finder.routes.export',
        'tkdn_finder.routes.health',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'Pillow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='tkdn-finder',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
